# Generated by Django 4.0.1 on 2022-02-09 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_students_info", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.UUIDField(),
        ),
    ]
