# Generated by Django 4.0.1 on 2022-02-09 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_students_info", "0005_alter_student_student_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.CharField(editable=False, max_length=20),
        ),
    ]
