# Generated by Django 4.0.1 on 2022-02-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_students_info", "0010_remove_student_id_alter_student_student_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="students_counter",
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
