# Generated by Django 4.0.2 on 2022-02-09 09:47

from django.db import migrations, models
import school_students_info.validators


class Migration(migrations.Migration):

    dependencies = [
        ("school_students_info", "0013_alter_school_students_counter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="students_counter",
            field=models.PositiveBigIntegerField(
                default=0,
                editable=False,
                validators=[school_students_info.validators.validate_greater_than_zero],
            ),
        ),
    ]
