# Generated by Django 4.0.2 on 2022-02-10 10:59

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import school_students_info.validators


class Migration(migrations.Migration):

    dependencies = [
        ("school_students_info", "0014_alter_school_students_counter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="max_students",
            field=models.PositiveBigIntegerField(
                validators=[school_students_info.validators.validate_greater_than_zero]
            ),
        ),
        migrations.AlterField(
            model_name="school",
            name="students_counter",
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.CreateModel(
            name="StudentDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nationality", django_countries.fields.CountryField(max_length=2)),
                ("birthdate", models.DateField()),
                ("age", models.PositiveIntegerField(editable=False)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school_students_info.student",
                    ),
                ),
            ],
        ),
    ]
