# Generated by Django 4.0.2 on 2022-02-10 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school_students_info", "0015_alter_school_max_students_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="StudentDetails",
            new_name="StudentDetail",
        ),
    ]
