# Generated by Django 4.0.2 on 2022-02-10 12:22

import datetime
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("school_students_info", "0016_rename_studentdetails_studentdetail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentdetail",
            name="age",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="studentdetail",
            name="birthdate",
            field=models.DateField(default=datetime.date(1900, 1, 1)),
        ),
        migrations.AlterField(
            model_name="studentdetail",
            name="nationality",
            field=django_countries.fields.CountryField(default="PH", max_length=2),
        ),
    ]
