# Generated by Django 4.0.2 on 2022-02-10 14:58

import datetime
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("school_students_info", "0017_alter_studentdetail_age_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="age",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="student",
            name="birthdate",
            field=models.DateField(default=datetime.date(1900, 1, 1)),
        ),
        migrations.AddField(
            model_name="student",
            name="nationality",
            field=django_countries.fields.CountryField(default="PH", max_length=2),
        ),
        migrations.DeleteModel(
            name="StudentDetail",
        ),
    ]
