# Generated by Django 4.0.2 on 2022-02-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "school_students_info",
            "0018_student_age_student_birthdate_student_nationality_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="age",
        ),
        migrations.AlterField(
            model_name="student",
            name="birthdate",
            field=models.DateField(null=True),
        ),
    ]
